<a href="https://colab.research.google.com/github/SATHISHKUMAR71/Customer_Leaving_problem/blob/main/Customer_Leaving_Problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#importing libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

tf.__version__

'2.12.0'

# Data Preprocessing

In [ ]:
dataset = pd.read_csv("Churn_Modelling.csv")
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
print(x)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


# Encoding Categorical Data

Encoding Gender

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [ ]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


one hot encoding for Geography

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#ANN

In [ ]:
Artificial_NN = tf.keras.models.Sequential()

In [ ]:
Artificial_NN.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
Artificial_NN.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [ ]:
Artificial_NN.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Compiling the NN

In [ ]:
Artificial_NN.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Training the Aritificial_NN

In [ ]:
Artificial_NN.fit(X_train, y_train, batch_size = 32, epochs = 400)

Epoch 1/400
250/250 [==============================] - 0s 2ms/step - loss: 0.3392 - accuracy: 0.8621
Epoch 2/400
250/250 [==============================] - 0s 1ms/step - loss: 0.3387 - accuracy: 0.8611
Epoch 3/400
250/250 [==============================] - 0s 2ms/step - loss: 0.3385 - accuracy: 0.8641
Epoch 4/400
250/250 [==============================] - 0s 1ms/step - loss: 0.3388 - accuracy: 0.8620
Epoch 5/400
250/250 [==============================] - 0s 1ms/step - loss: 0.3386 - accuracy: 0.8624
Epoch 6/400
250/250 [==============================] - 0s 1ms/step - loss: 0.3379 - accuracy: 0.8624
Epoch 7/400
250/250 [==============================] - 1s 2ms/step - loss: 0.3384 - accuracy: 0.8614
Epoch 8/400
250/250 [==============================] - 0s 2ms/step - loss: 0.3381 - accuracy: 0.8634
Epoch 9/400
250/250 [==============================] - 1s 4ms/step - loss: 0.3375 - accuracy: 0.8622
Epoch 10/400
250/250 [==============================] - 1s 3ms/step - loss: 0.3381 - accura

#Predict

In [ ]:
print(Artificial_NN.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))>0.5)

1/1 [==============================] - 0s 18ms/step
[[False]]
